# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exegesis/proto/instruction_encoding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exegesis/proto/instruction_encoding.proto',
  package='exegesis',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)exegesis/proto/instruction_encoding.proto\x12\x08\x65xegesis\"\xf6\x03\n\x1a\x46ixedSizeInstructionLayout\x12\x11\n\tform_name\x18\x01 \x01(\t\x12\x41\n\nbit_ranges\x18\x02 \x03(\x0b\x32-.exegesis.FixedSizeInstructionLayout.BitRange\x1a\x81\x03\n\x08\x42itRange\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03msb\x18\x02 \x01(\x05\x12\x0b\n\x03lsb\x18\x03 \x01(\x05\x12K\n\x07pattern\x18\x04 \x01(\x0b\x32\x38.exegesis.FixedSizeInstructionLayout.BitRange.BitPatternH\x00\x12O\n\x0bnot_pattern\x18\x05 \x01(\x0b\x32\x38.exegesis.FixedSizeInstructionLayout.BitRange.BitPatternH\x00\x1a\x9f\x01\n\nBitPattern\x12J\n\x04\x62its\x18\x01 \x03(\x0e\x32<.exegesis.FixedSizeInstructionLayout.BitRange.BitPattern.Bit\"E\n\x03\x42it\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x43ONSTANT_ONE\x10\x01\x12\x11\n\rCONSTANT_ZERO\x10\x02\x12\x0c\n\x08VARIABLE\x10\x03\x42\r\n\x0b\x63onstraintsb\x06proto3')
)



_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN_BIT = _descriptor.EnumDescriptor(
  name='Bit',
  full_name='exegesis.FixedSizeInstructionLayout.BitRange.BitPattern.Bit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANT_ONE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANT_ZERO', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VARIABLE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=474,
  serialized_end=543,
)
_sym_db.RegisterEnumDescriptor(_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN_BIT)


_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN = _descriptor.Descriptor(
  name='BitPattern',
  full_name='exegesis.FixedSizeInstructionLayout.BitRange.BitPattern',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bits', full_name='exegesis.FixedSizeInstructionLayout.BitRange.BitPattern.bits', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN_BIT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=543,
)

_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE = _descriptor.Descriptor(
  name='BitRange',
  full_name='exegesis.FixedSizeInstructionLayout.BitRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='exegesis.FixedSizeInstructionLayout.BitRange.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msb', full_name='exegesis.FixedSizeInstructionLayout.BitRange.msb', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lsb', full_name='exegesis.FixedSizeInstructionLayout.BitRange.lsb', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='exegesis.FixedSizeInstructionLayout.BitRange.pattern', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='not_pattern', full_name='exegesis.FixedSizeInstructionLayout.BitRange.not_pattern', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='constraints', full_name='exegesis.FixedSizeInstructionLayout.BitRange.constraints',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=173,
  serialized_end=558,
)

_FIXEDSIZEINSTRUCTIONLAYOUT = _descriptor.Descriptor(
  name='FixedSizeInstructionLayout',
  full_name='exegesis.FixedSizeInstructionLayout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='form_name', full_name='exegesis.FixedSizeInstructionLayout.form_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bit_ranges', full_name='exegesis.FixedSizeInstructionLayout.bit_ranges', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=558,
)

_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN.fields_by_name['bits'].enum_type = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN_BIT
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN.containing_type = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN_BIT.containing_type = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.fields_by_name['pattern'].message_type = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.fields_by_name['not_pattern'].message_type = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.containing_type = _FIXEDSIZEINSTRUCTIONLAYOUT
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.oneofs_by_name['constraints'].fields.append(
  _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.fields_by_name['pattern'])
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.fields_by_name['pattern'].containing_oneof = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.oneofs_by_name['constraints']
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.oneofs_by_name['constraints'].fields.append(
  _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.fields_by_name['not_pattern'])
_FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.fields_by_name['not_pattern'].containing_oneof = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE.oneofs_by_name['constraints']
_FIXEDSIZEINSTRUCTIONLAYOUT.fields_by_name['bit_ranges'].message_type = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE
DESCRIPTOR.message_types_by_name['FixedSizeInstructionLayout'] = _FIXEDSIZEINSTRUCTIONLAYOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FixedSizeInstructionLayout = _reflection.GeneratedProtocolMessageType('FixedSizeInstructionLayout', (_message.Message,), dict(

  BitRange = _reflection.GeneratedProtocolMessageType('BitRange', (_message.Message,), dict(

    BitPattern = _reflection.GeneratedProtocolMessageType('BitPattern', (_message.Message,), dict(
      DESCRIPTOR = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE_BITPATTERN,
      __module__ = 'exegesis.proto.instruction_encoding_pb2'
      # @@protoc_insertion_point(class_scope:exegesis.FixedSizeInstructionLayout.BitRange.BitPattern)
      ))
    ,
    DESCRIPTOR = _FIXEDSIZEINSTRUCTIONLAYOUT_BITRANGE,
    __module__ = 'exegesis.proto.instruction_encoding_pb2'
    # @@protoc_insertion_point(class_scope:exegesis.FixedSizeInstructionLayout.BitRange)
    ))
  ,
  DESCRIPTOR = _FIXEDSIZEINSTRUCTIONLAYOUT,
  __module__ = 'exegesis.proto.instruction_encoding_pb2'
  # @@protoc_insertion_point(class_scope:exegesis.FixedSizeInstructionLayout)
  ))
_sym_db.RegisterMessage(FixedSizeInstructionLayout)
_sym_db.RegisterMessage(FixedSizeInstructionLayout.BitRange)
_sym_db.RegisterMessage(FixedSizeInstructionLayout.BitRange.BitPattern)


# @@protoc_insertion_point(module_scope)
